# Generated by Django 4.1.5 on 2023-01-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
