# Generated by Django 4.1.5 on 2023-01-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerDemo',
        ),
    ]
