# Generated by Django 4.1.5 on 2023-01-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0002_delete_buyerdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('pic', models.FileField(default='avatar.jpg', upload_to='buyer_profiles')),
            ],
        ),
    ]
